name: Update README.md

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install requests
    - name: Download README
      run: python push.py
    - name: Commit and Push
      run: |
        git config --global user.name "acymz"
        git config --global user.email "cymz6@hotmail.com"
        git add README.md
        git commit -m "Update README.md"
        git push
